NEWS = [
    ("Optimism in European tech stocks due to an upcoming conference.", "ETI", 1.05, 0.95, 1.05),
    ("Rumored advancements in European electric vehicles.", "EAI", 1.03, 0.97, 1.03),
    ("Healthcare companies show promise due to potential vaccine breakthroughs.", "GHI", 1.04, 0.98, 1.02),
    ("Possible political tensions might weaken the Euro.", "EURUSD", 0.98, 0.99, 1.01),
    ("European tech companies report higher than expected profits.", "ETI", 1.06, 0.94, 1.06),
    ("Surge in 5G adoption pushes European Tech Index upwards.", "ETI", 1.05, 0.99, 1.05),
    ("New European emission standards threaten traditional automotive stocks.", "EAI", 0.93, 0.87, 0.99),
    ("Groundbreaking research in AI drives the ETI to new heights.", "ETI", 1.09, 1.05, 1.13),
    ("Economic sanctions against a major EU country causes Euro to dip.", "EURUSD", 0.95, 0.93, 0.97),
    ("European car manufacturers announce a collaborative electric vehicle project.", "EAI", 1.07, 1.03, 1.09),
    ("Major tech company suffers a data breach, leading to ETI drop.", "ETI", 0.94, 0.90, 0.98),
    ("Record growth reported in European pharmaceuticals boosting GHI.", "GHI", 1.08, 1.04, 1.10),
    ("Rumors of a major bank insolvency weakens the Euro.", "EURUSD", 0.97, 0.95, 0.99),
    ("European automotive stocks rebound with the announcement of a new hybrid model.", "EAI", 1.06, 1.02, 1.08),
    ("A major tech firm announces breakthroughs in quantum computing.", "ETI", 1.11, 1.07, 1.15),
    ("Economic indicators point to a robust growth period for the Euro.", "EURUSD", 1.04, 1.02, 1.06),
    ("Potential trade deals with Asian markets boost European automotive stocks.", "EAI", 1.05, 1.01, 1.07),
    ("Concerns over healthcare regulations lead to volatility in GHI.", "GHI", 0.97, 0.93, 1.01),
    ("Major tech conference in Amsterdam leads to a bullish trend in ETI.", "ETI", 1.05, 1.01, 1.07),
    ("Outbreak of a health epidemic causes sudden drop in European automotive travel.", "EAI", 0.92, 0.88, 0.96),
    ("Rising oil prices lead to increased interest in electric vehicles.", "EAI", 1.06, 1.02, 1.08),
    ("Sudden resurgence of the Euro against global currencies.", "EURUSD", 1.06, 1.04, 1.08),
    ("Tech Index sees a dip as antitrust investigations begin in the EU.", "ETI", 0.95, 0.91, 0.99),
    ("Renewed trade agreements boost sentiments for European automakers.", "EAI", 1.04, 1.00, 1.06),
    ("Revolutionary AI-driven drug discovery boosts GHI.", "GHI", 1.09, 1.05, 1.13),
    ("Tech CEOs hold a dance-off at a conference. Stocks groove upwards.", "ETI", 1.05, 0.95, 1.05),
    ("Unconfirmed reports: European electric cars now run on gossip.", "EAI", 1.03, 0.97, 1.03),
    ("A 'possible' new vaccine promises to combat baldness and snoring.", "GHI", 1.04, 0.98, 1.02),
    ("Euro wobbles after a politician mistook it for a new dance move.", "EURUSD", 0.98, 0.99, 1.01),
    ("European tech CEOs sell lemonade; profits unexpectedly soar.", "ETI", 1.06, 0.94, 1.06),
    ("5G towers rumored to be excellent places to dry clothes. Stocks rise.", "ETI", 1.05, 0.99, 1.05),
    ("European cars may have to pass the 'can they roll silently?' test. Stocks jitter.", "EAI", 0.93, 0.87, 0.99),
    ("AI claims to have found the meaning of life. Spoiler: It’s 42. Tech goes wild.", "ETI", 1.09, 1.05, 1.13),
    ("EU country allegedly accepts magic beans as currency. Euro trips.", "EURUSD", 0.95, 0.93, 0.97),
    ("European car makers' new project: Convertibles for ducks. Stocks flap upwards.", "EAI", 1.07, 1.03, 1.09),
    ("Tech company's data breach exposes everyone's embarrassing playlists.", "ETI", 0.94, 0.90, 0.98),
    ("GHI stocks rise as Europe apparently finds a cure for 'Monday blues'.", "GHI", 1.08, 1.04, 1.10),
    ("Rumors swirl: A major bank's vault contains just one rubber duck. Euro quacks.", "EURUSD", 0.97, 0.95, 0.99),
    ("European cars now come with a 'selfie' mode. Stocks snap upwards.", "EAI", 1.06, 1.02, 1.08),
    ("Tech firm reveals breakthrough in quantum computing: Computers can now feel shame.", "ETI", 1.11, 1.07, 1.15),
    ("Euro strengthens as politicians discover a pot of gold. (Rainbows involved.)", "EURUSD", 1.04, 1.02, 1.06),
    ("Asian markets now accepting spaghetti for European cars. Stocks boil.", "EAI", 1.05, 1.01, 1.07),
    ("GHI companies unsure if laughter really is the best medicine. Stocks chuckle.", "GHI", 0.97, 0.93, 1.01),
    ("Tech conference gives out free socks. The market goes toe-tally crazy.", "ETI", 1.05, 1.01, 1.07),
    ("Reports claim European cars allergic to new superbug. Stocks sneeze.", "EAI", 0.92, 0.88, 0.96),
    ("Oil prices surge. Electric cars now come with complimentary essential oil kits.", "EAI", 1.06, 1.02, 1.08),
    ("Euro strengthens after a witch cast a prosperity spell (may involve fairy dust).", "EURUSD", 1.06, 1.04, 1.08),
    ("Tech stocks dip after a robot claims to have developed emotions.", "ETI", 0.95, 0.91, 0.99),
    ("Trade agreements involve swapping chocolates for cars. Everyone wins!", "EAI", 1.04, 1.00, 1.06),
    ("AI claims to have found a miracle drug: Chocolate! Healthcare celebrates.", "GHI", 1.09, 1.05, 1.13),
]
DISASTERS = [
    ("A major earthquake hits the Frankfurt Market, causing a sharp drop in EAI prices.", "EAI", 0.8, 0.9, 1.1),
    ("A cyber attack on the Amsterdam Market causes a temporary shutdown, leading to a drop in ETI prices.", "ETI", 0.9, 0.8, 1.2),
    ("A major healthcare scandal involving a GHI company causes a drop in GHI prices.", "GHI", 0.95, 0.9, 1.1),
    ("A major bank collapse in the EU causes uncertainty in the markets.", "EURUSD", 0.9, 0.85, 0.95),
    ("Large-scale protests disrupt operations in major European tech hubs.", "ETI", 0.93, 0.88, 0.98),
    ("New trade tariffs imposed lead to a plummet in EAI stock values.", "EAI", 0.88, 0.83, 0.93),
    ("Stringent data privacy laws lead to a slump in tech stock values.", "ETI", 0.92, 0.87, 0.97),
    ("Major auto recall due to defective components hits EAI hard.", "EAI", 0.85, 0.80, 0.90),
    ("Global economic slowdown impacts European automotive stocks.", "EAI", 0.89, 0.84, 0.94),
    ("Outbreak of a contagious disease affects European health stocks.", "GHI", 0.87, 0.82, 0.92),
    ("A major tech company goes bankrupt, pulling the ETI down.", "ETI", 0.9, 0.85, 0.95),
    ("Fraudulent activities reported by a leading healthcare company.", "GHI", 0.88, 0.83, 0.93),
    ("Unexpected strengthening of other global currencies weakens the Euro.", "EURUSD", 0.91, 0.86, 0.96),
    ("Tech companies face hefty fines due to regulatory violations.", "ETI", 0.94, 0.89, 0.99),
    ("International trade wars lead to a sharp decline in EAI.", "EAI", 0.86, 0.81, 0.91),
    ("Labor strikes at major tech firms disrupt the market.", "ETI", 0.92, 0.87, 0.97),
    ("Unfavorable patent rulings affect major companies in GHI.", "GHI", 0.9, 0.85, 0.95),
    ("Oil price surge negatively impacts the European automotive industry.", "EAI", 0.87, 0.82, 0.92),
    ("Major data breach affects multiple European tech companies.", "ETI", 0.93, 0.88, 0.98),
    ("Geopolitical tensions in EU member countries lead to a weak Euro.", "EURUSD", 0.89, 0.84, 0.94),
    ("Natural disaster disrupts production lines for major automakers.", "EAI", 0.88, 0.83, 0.93),
    ("A sudden downturn in the global economy impacts European markets.", "ETI", 0.9, 0.85, 0.95),
    ("Legal challenges and lawsuits plague the healthcare index.", "GHI", 0.91, 0.86, 0.96),
    ("Economic instability in the EU leads to a decline in EURUSD.", "EURUSD", 0.92, 0.87, 0.97),
    ("Supply chain disruptions hit the automotive industry.", "EAI", 0.93, 0.88, 0.98),
    ("Major security vulnerabilities discovered in popular software products.", "ETI", 0.94, 0.89, 0.99),
    ("Regulatory crackdown on healthcare pricing hits GHI.", "GHI", 0.9, 0.85, 0.95),
    ("Political unrest in major European nations weakens the Euro.", "EURUSD", 0.91, 0.86, 0.96),
    ("Major European tech firm implicated in a tax evasion scandal.", "ETI", 0.92, 0.87, 0.97),
    ("Emission cheating scandal resurfaces, impacting automotive stocks.", "EAI", 0.9, 0.85, 0.95),
    ("Adverse drug reactions reported for a popular medicine, GHI affected.", "GHI", 0.91, 0.86, 0.96),
    ("Unexpected interest rate hikes by the ECB lead to Euro volatility.", "EURUSD", 0.92, 0.87, 0.97),
    ("Banking crisis in a major EU country affects overall market confidence.", "EURUSD", 0.9, 0.85, 0.95),
    ("Bankruptcy of a major car manufacturer sends shockwaves in EAI.", "EAI", 0.88, 0.83, 0.93),
    ("Scandal involving unethical clinical trials hits healthcare index.", "GHI", 0.87, 0.82, 0.92),
    ("Trade embargos impact the European automotive industry.", "EAI", 0.86, 0.81, 0.91),
    ("Major tech firms face antitrust regulations, ETI feels the heat.", "ETI", 0.85, 0.80, 0.90),
    ("Environmental concerns lead to strict regulations, impacting EAI.", "EAI", 0.84, 0.79, 0.89),
    ("Major cyberattacks disrupt services of prominent tech companies.", "ETI", 0.83, 0.78, 0.88),
    ("Lingering Brexit issues lead to a weaker Euro.", "EURUSD", 0.82, 0.77, 0.87),
    ("Strict drug approval processes lead to uncertainty in GHI.", "GHI", 0.81, 0.76, 0.86),
    ("Frankfurt Market rattled as Godzilla allegedly stomps by. EAI stocks flee.", "EAI", 0.8, 0.9, 1.1),
    ("Amsterdam Market suffers cyber attack; culprit reportedly a rogue Roomba.", "ETI", 0.9, 0.8, 1.2),
    ("Healthcare scandal: GHI company accused of using chocolate placebo pills.", "GHI", 0.95, 0.9, 1.1),
    ("EU banks collapse: CEO found investing in magical beans.", "EURUSD", 0.9, 0.85, 0.95),
    ("Protests erupt as tech hubs ban coffee. Productivity plummets.", "ETI", 0.93, 0.88, 0.98),
    ("New tariffs imposed: Importing virtual pixels now heavily taxed. EAI cries.", "EAI", 0.88, 0.83, 0.93),
    ("Privacy laws now require hiding all unsightly tech. Stocks hide too.", "ETI", 0.92, 0.87, 0.97),
    ("Auto recall: Cars mistakenly fitted with square wheels. EAI goes round in circles.", "EAI", 0.85, 0.80, 0.90),
    ("Global economy slows down. Blame placed on turtles. Cars can't keep up.", "EAI", 0.89, 0.84, 0.94),
    ("Disease outbreak: Common cold allegedly weaponized. Health stocks sneeze.", "GHI", 0.87, 0.82, 0.92),
    ("Tech company goes bankrupt; spent all on invisible gadgets.", "ETI", 0.9, 0.85, 0.95),
    ("Leading healthcare company's newest drug? Glitter pills. Market isn't dazzled.", "GHI", 0.88, 0.83, 0.93),
    ("Euro weakens as global currencies hit the gym.", "EURUSD", 0.91, 0.86, 0.96),
    ("Tech companies fined for trying to replace programmers with hamsters.", "ETI", 0.94, 0.89, 0.99),
    ("Trade wars intensify: Europe now exporting snow to Antarctica. EAI chills.", "EAI", 0.86, 0.81, 0.91),
    ("Tech firms' new strategy: Hiring cats to walk on keyboards. Market disapproves.", "ETI", 0.92, 0.87, 0.97),
    ("Patent ruling: GHI cannot patent the 'chicken soup for flu' remedy.", "GHI", 0.9, 0.85, 0.95),
    ("Oil prices surge: Rumor has it, European cars now run on tears.", "EAI", 0.87, 0.82, 0.92),
    ("Data breach: European tech companies’ secret cookie recipes exposed!", "ETI", 0.93, 0.88, 0.98),
    ("EU countries play heated games of Monopoly, causing real economic tension.", "EURUSD", 0.89, 0.84, 0.94),
    ("Natural disaster: Moths eat fabric of reality, automotive production halts.", "EAI", 0.88, 0.83, 0.93),
    ("Global economy downturn: Aliens supposedly found Earth 'meh'.", "ETI", 0.9, 0.85, 0.95),
    ("Lawsuits allege healthcare companies making potions. No magic seen in stocks.", "GHI", 0.91, 0.86, 0.96),
    ("Economic instability: EU countries now trading in candy wrappers.", "EURUSD", 0.92, 0.87, 0.97),
    ("Automotive industry rocked: Supply chains replaced with paper clips.", "EAI", 0.93, 0.88, 0.98),
    ("Software's new major vulnerability: They’re ticklish.", "ETI", 0.94, 0.89, 0.99),
    ("Healthcare pricing scandal: Band-aids apparently made of gold.", "GHI", 0.9, 0.85, 0.95),
    ("Political unrest: EU leaders now resolve issues with rock-paper-scissors.", "EURUSD", 0.91, 0.86, 0.96),
    ("Tech firm's tax evasion strategy? Storing money in virtual piggy banks.", "ETI", 0.92, 0.87, 0.97),
    ("Cars caught cheating emissions by using perfume. EAI doesn't smell right.", "EAI", 0.9, 0.85, 0.95),
    ("Adverse drug reactions: Patients can't stop quacking post-medication.", "GHI", 0.91, 0.86, 0.96),
    ("ECB hikes interest rates, claims they’re just 'following their hiking passion'.", "EURUSD", 0.92, 0.87, 0.97),    
]
MIRACLES = [
    ("A breakthrough in electric vehicle technology leads to a surge in EAI prices.", "EAI", 1.2, 1.1, 1.3),
    ("A major tech company announces a revolutionary new product, leading to a surge in ETI prices.", "ETI", 1.3, 1.2, 1.4),
    ("A new vaccine is approved by a GHI company, leading to a surge in GHI prices.", "GHI", 1.1, 1.05, 1.15),
    ("Major European tech companies merge, promising innovative breakthroughs.", "ETI", 1.15, 1.10, 1.20),
    ("The EU announces substantial incentives for electric vehicle adoption.", "EAI", 1.2, 1.15, 1.25),
    ("Groundbreaking research promises to drastically reduce disease mortality rates.", "GHI", 1.3, 1.25, 1.35),
    ("The Euro gains as EU countries report record economic growth.", "EURUSD", 1.1, 1.07, 1.13),
    ("A major tech company announces successful quantum computing results.", "ETI", 1.25, 1.2, 1.3),
    ("New environmentally-friendly fuel developed, boosting European auto stocks.", "EAI", 1.18, 1.13, 1.23),
    ("Europe leads in global healthcare innovation with new treatment methodologies.", "GHI", 1.22, 1.17, 1.27),
    ("Major investment into European tech startups promises a bright future for ETI.", "ETI", 1.17, 1.12, 1.22),
    ("Revolutionary battery technology announced, a win for the European auto industry.", "EAI", 1.23, 1.18, 1.28),
    ("European healthcare companies announce collaboration for global health initiatives.", "GHI", 1.2, 1.15, 1.25),
    ("The Euro strengthens due to positive international trade agreements.", "EURUSD", 1.08, 1.05, 1.11),
    ("New AI-driven technologies position Europe as a global tech leader.", "ETI", 1.19, 1.14, 1.24),
    ("The automotive industry sees a boom due to European international exports.", "EAI", 1.21, 1.16, 1.26),
    ("Pioneering medical research positions Europe as a global healthcare leader.", "GHI", 1.24, 1.19, 1.29),
    ("Strong international investments boost the value of the Euro.", "EURUSD", 1.09, 1.06, 1.12),
    ("Major tech companies expand into new sectors, leading to a bullish trend for ETI.", "ETI", 1.18, 1.13, 1.23),
    ("Breakthrough in sustainable fuel sources gives the European auto industry an edge.", "EAI", 1.25, 1.20, 1.30),
    ("Healthcare firms report groundbreaking success in combating chronic diseases.", "GHI", 1.23, 1.18, 1.28),
    ("Euro gains traction with positive financial reforms in the EU.", "EURUSD", 1.07, 1.04, 1.10),
    ("Significant advancements in AI and robotics drive ETI upwards.", "ETI", 1.22, 1.17, 1.27),
    ("Green automotive tech positions European automakers as global leaders.", "EAI", 1.24, 1.19, 1.29),
    ("Major medical advancements promise increased lifespan.", "GHI", 1.26, 1.21, 1.31),
    ("Foreign investments boost the strength and value of the Euro.", "EURUSD", 1.08, 1.05, 1.11),
    ("Major tech breakthroughs announce Europe as a leader in global tech.", "ETI", 1.27, 1.22, 1.32),
    ("New eco-friendly automotive models are a hit globally.", "EAI", 1.26, 1.21, 1.31),
    ("European healthcare pioneers a new era of treatments.", "GHI", 1.28, 1.23, 1.33),
    ("Economic strength and stability position the Euro as a leading global currency.", "EURUSD", 1.09, 1.06, 1.12),
    ("Digital revolution in Europe leads to a surge in the tech industry.", "ETI", 1.29, 1.24, 1.34),
    ("European automakers lead in global sales and innovation.", "EAI", 1.28, 1.23, 1.33),
    ("Healthcare innovation in Europe receives global accolades.", "GHI", 1.30, 1.25, 1.35),
    ("Trade deals and partnerships strengthen the Euro's global position.", "EURUSD", 1.1, 1.07, 1.13),
    ("Innovations in cloud technologies put European tech firms in the spotlight.", "ETI", 1.3, 1.25, 1.35),
    ("Clean energy cars from Europe set sales records.", "EAI", 1.29, 1.24, 1.34),
    ("European healthcare becomes a model for global health systems.", "GHI", 1.31, 1.26, 1.36),
    ("Economic growth and investments lead to a bullish Euro.", "EURUSD", 1.11, 1.08, 1.14),
    ("European tech firms lead in the development of sustainable technologies.", "ETI", 1.32, 1.27, 1.37),
    ("Surge in demand for European automotive brands globally.", "EAI", 1.3, 1.25, 1.35),
    ("Aliens demand European electric cars; EAI rockets.", "EAI", 1.2, 1.1, 1.3),
    ("Tech company invents teleportation! ETI teleports to new heights.", "ETI", 1.3, 1.2, 1.4),
    ("New GHI vaccine promises immortality. Death rates plummet!", "GHI", 1.1, 1.05, 1.15),
    ("European tech giants merge to form 'Mega-Ultra-Cybernetic Corp.' Excitement builds.", "ETI", 1.15, 1.10, 1.20),
    ("EU subsidizes electric cars. Free unicorn with every purchase!", "EAI", 1.2, 1.15, 1.25),
    ("New research: Staring at broccoli reduces disease! GHI thrives.", "GHI", 1.3, 1.25, 1.35),
    ("Euro gets buff; spotted doing bicep curls.", "EURUSD", 1.1, 1.07, 1.13),
    ("Tech company masters time travel. Next week's profits already in!", "ETI", 1.25, 1.2, 1.3),
    ("Europe introduces car fuelled by love and good vibes.", "EAI", 1.18, 1.13, 1.23),
    ("Europe invents health potion; no more colds!", "GHI", 1.22, 1.17, 1.27),
    ("Europe's tech startups to launch moon base. ETI over the moon!", "ETI", 1.17, 1.12, 1.22),
    ("Battery breakthrough: Cars now run on pure enthusiasm.", "EAI", 1.23, 1.18, 1.28),
    ("European healthcare to heal with magic dust. Global health applauds.", "GHI", 1.2, 1.15, 1.25),
    ("Euro joins dance-off, globally acclaimed.", "EURUSD", 1.08, 1.05, 1.11),
    ("Europe invents sentient AI; it loves cat videos.", "ETI", 1.19, 1.14, 1.24),
    ("Europe's cars now fly. Road traffic? So yesterday.", "EAI", 1.21, 1.16, 1.26),
    ("Medics use pixie dust for treatments; chronic diseases vanish.", "GHI", 1.24, 1.19, 1.29),
    ("Euro wins 'Miss Universe Currency' pageant.", "EURUSD", 1.09, 1.06, 1.12),
    ("European tech now powered by dreams. Unicorn dreams to be precise.", "ETI", 1.18, 1.13, 1.23),
    ("Europe's new fuel? Pure, concentrated rainbows.", "EAI", 1.25, 1.20, 1.30),
    ("GHI solves common cold by inventing 'sneeze teleportation'.", "GHI", 1.23, 1.18, 1.28),
    ("Euro gets power-up; levels up!", "EURUSD", 1.07, 1.04, 1.10),
    ("Europe unveils robot unicorns; tech industry goes wild!", "ETI", 1.22, 1.17, 1.27),
    ("Europe's cars now purr. Literally, they’re half cat.", "EAI", 1.24, 1.19, 1.29),
    ("New medical treatment: Spontaneous dance routines.", "GHI", 1.26, 1.21, 1.31),
    ("Euro considered as new global 'cool' icon.", "EURUSD", 1.08, 1.05, 1.11),
    ("European tech creates 'Instant Mood-Boost' button.", "ETI", 1.27, 1.22, 1.32),
    ("Europe's cars now change color based on mood.", "EAI", 1.26, 1.21, 1.31),
    ("European doctors replace medicine with laughter pills.", "GHI", 1.28, 1.23, 1.33),
    ("Euro found doing yoga; inner strength on fleek.", "EURUSD", 1.09, 1.06, 1.12),
    ("European tech launches WiFi that runs on good vibes.", "ETI", 1.29, 1.24, 1.34),
    ("European cars now self-aware; ask for weekends off.", "EAI", 1.28, 1.23, 1.33),
    ("Doctors in Europe replace stethoscopes with magic wands.", "GHI", 1.30, 1.25, 1.35),
    ("Euro charms global currencies with its charisma.", "EURUSD", 1.1, 1.07, 1.13),
    ("Europe introduces cloudless cloud tech; actual clouds!", "ETI", 1.32, 1.27, 1.37),
    ("European cars win global fashion show. Elegance on wheels.", "EAI", 1.3, 1.25, 1.35)
]